# Generated by Django 3.1.2 on 2021-03-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Api_url', models.CharField(max_length=256)),
                ('Method', models.CharField(max_length=50)),
                ('User_email', models.EmailField(max_length=254)),
                ('Milliseconds', models.IntegerField()),
                ('Code', models.IntegerField()),
                ('User_agent', models.CharField(max_length=256)),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='usage_log',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.CharField(max_length=256)),
                ('Month', models.DateField()),
                ('Source', models.CharField(max_length=256)),
                ('Total_calls', models.IntegerField()),
                ('First_api_call', models.DateTimeField()),
                ('Last_api_call', models.DateTimeField()),
                ('Last_checked_row', models.IntegerField()),
            ],
        ),
    ]
