# Generated by Django 3.1.2 on 2021-03-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('four_table_app', '0002_auto_20210305_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log_entry',
            name='Time',
            field=models.CharField(max_length=256),
        ),
    ]
